import type { Locale } from "@/config/site";

const fr = {
  addToCart: "Ajouter au panier",
  adding: "Ajout…",
  added: "Ajouté à votre sélection",
  outOfStock: "Épuisé",
  inStock: "En stock",
  onlyLeft: (n: number) => `Plus que ${n} exemplaire${n > 1 ? "s" : ""}`,
  lowStockNote: "Forte demande sur cette référence",
  wishlist: "Wishlist",
  compare: "Comparer",
  share: "Partager",
  copyLink: "Copier le lien",
  linkCopied: "Lien copié",
  specSheet: "Fiche technique",
  printPage: "Imprimer",
  dialColor: "Cadran",
  strap: "Bracelet",
  caseSize: "Boîtier",
  limitedEdition: "Édition limitée",
  newArrival: "Nouveauté",
  deliveryEstimate: "Livraison estimée",
  deliveryExpress: "Express 24–48h à Casablanca & Rabat",
  authenticity: "Authenticité certifiée",
  warranty: (m: number) => `Garantie ${m} mois`,
  returns: "Retours sous 14 jours",
  securePayment: "Paiement sécurisé & COD",
  reviews: "Avis",
  verifiedPurchase: "Achat vérifié",
  allRatings: "Toutes les notes",
  withPhotos: "Avec photos",
  verifiedOnly: "Achats vérifiés",
  noReviews: "Aucun avis pour cette sélection.",
  questions: "Questions & Réponses",
  askedBy: "Posée par",
  official: "Maison LORVEX",
  noQuestions: "Aucune question pour le moment.",
  faq: "Questions fréquentes",
  craftsmanship: "Savoir-faire",
  movementSection: "Mouvement",
  materials: "Matériaux",
  dimensions: "Dimensions",
  waterResistance: "Étanchéité",
  warrantySection: "Garantie & Service",
  packaging: "Écrin & Présentation",
  packagingBody:
    "Chaque pièce est livrée dans un écrin muséal signé LORVEX, accompagnée de son certificat d'authenticité, de sa documentation et d'un gant de manipulation.",
  frequentlyBought: "Souvent acquis ensemble",
  aiPicks: "Sélection personnalisée",
  aiPicksSub: "Recommandé par notre algorithme selon cette pièce",
  relatedCollections: "Collections associées",
  recentlyViewed: "Vus récemment",
  viewing: (n: number) => `${n} personne${n > 1 ? "s" : ""} consulte${n > 1 ? "nt" : ""} cette pièce`,
  recentPurchase: (name: string, city: string) => `${name} de ${city} vient d'acquérir`,
  minutesAgo: (m: number) => (m < 2 ? "à l'instant" : `il y a ${m} min`),
  youMayLike: "Vous apprécierez aussi",
  selectedForYou: "Sélectionné pour vous",
  exploreCollection: "Explorer la collection",
  discoverMore: "Découvrir",
};

type PdpStrings = { [K in keyof typeof fr]: (typeof fr)[K] };

const en: PdpStrings = {
  addToCart: "Add to cart",
  adding: "Adding…",
  added: "Added to your selection",
  outOfStock: "Out of stock",
  inStock: "In stock",
  onlyLeft: (n) => `Only ${n} left`,
  lowStockNote: "High demand on this reference",
  wishlist: "Wishlist",
  compare: "Compare",
  share: "Share",
  copyLink: "Copy link",
  linkCopied: "Link copied",
  specSheet: "Spec sheet",
  printPage: "Print",
  dialColor: "Dial",
  strap: "Strap",
  caseSize: "Case",
  limitedEdition: "Limited edition",
  newArrival: "New arrival",
  deliveryEstimate: "Estimated delivery",
  deliveryExpress: "Express 24–48h in Casablanca & Rabat",
  authenticity: "Certified authenticity",
  warranty: (m) => `${m}-month warranty`,
  returns: "14-day returns",
  securePayment: "Secure payment & COD",
  reviews: "Reviews",
  verifiedPurchase: "Verified purchase",
  allRatings: "All ratings",
  withPhotos: "With photos",
  verifiedOnly: "Verified only",
  noReviews: "No reviews yet for this selection.",
  questions: "Questions & Answers",
  askedBy: "Asked by",
  official: "Maison LORVEX",
  noQuestions: "No questions yet.",
  faq: "Frequently asked questions",
  craftsmanship: "Craftsmanship",
  movementSection: "Movement",
  materials: "Materials",
  dimensions: "Dimensions",
  waterResistance: "Water resistance",
  warrantySection: "Warranty & Service",
  packaging: "Presentation box",
  packagingBody:
    "Each piece arrives in a museum-grade LORVEX presentation box, with its certificate of authenticity, documentation and handling gloves.",
  frequentlyBought: "Frequently bought together",
  aiPicks: "Curated for you",
  aiPicksSub: "Recommended by our algorithm based on this piece",
  relatedCollections: "Related collections",
  recentlyViewed: "Recently viewed",
  viewing: (n) => `${n} ${n > 1 ? "people are" : "person is"} viewing this piece`,
  recentPurchase: (name, city) => `${name} from ${city} just acquired`,
  minutesAgo: (m) => (m < 2 ? "just now" : `${m} min ago`),
  youMayLike: "You may also appreciate",
  selectedForYou: "Selected for you",
  exploreCollection: "Explore the collection",
  discoverMore: "Discover",
};

const ar: PdpStrings = {
  addToCart: "أضف إلى السلة",
  adding: "جارٍ الإضافة…",
  added: "أُضيفت إلى اختيارك",
  outOfStock: "نفدت الكمية",
  inStock: "متوفر",
  onlyLeft: (n) => `بقي ${n} فقط`,
  lowStockNote: "طلب مرتفع على هذه القطعة",
  wishlist: "المفضلة",
  compare: "مقارنة",
  share: "مشاركة",
  copyLink: "نسخ الرابط",
  linkCopied: "تم نسخ الرابط",
  specSheet: "الورقة التقنية",
  printPage: "طباعة",
  dialColor: "الميناء",
  strap: "السوار",
  caseSize: "العلبة",
  limitedEdition: "إصدار محدود",
  newArrival: "وصل حديثاً",
  deliveryEstimate: "التسليم المتوقع",
  deliveryExpress: "توصيل سريع 24–48س في الدار البيضاء والرباط",
  authenticity: "أصالة موثّقة",
  warranty: (m) => `ضمان ${m} شهراً`,
  returns: "إرجاع خلال 14 يوماً",
  securePayment: "دفع آمن والدفع عند الاستلام",
  reviews: "التقييمات",
  verifiedPurchase: "شراء موثّق",
  allRatings: "جميع التقييمات",
  withPhotos: "مع صور",
  verifiedOnly: "الموثّقة فقط",
  noReviews: "لا توجد تقييمات بعد.",
  questions: "أسئلة وأجوبة",
  askedBy: "سأل",
  official: "دار لورفكس",
  noQuestions: "لا توجد أسئلة بعد.",
  faq: "الأسئلة الشائعة",
  craftsmanship: "الحرفية",
  movementSection: "الحركة",
  materials: "المواد",
  dimensions: "الأبعاد",
  waterResistance: "مقاومة الماء",
  warrantySection: "الضمان والخدمة",
  packaging: "العلبة والتقديم",
  packagingBody:
    "تصل كل قطعة في علبة فاخرة موقّعة من لورفكس، مع شهادة الأصالة والوثائق وقفازات المناولة.",
  frequentlyBought: "يُقتنى معاً غالباً",
  aiPicks: "اختيار مخصص لك",
  aiPicksSub: "مقترح من خوارزميتنا بناءً على هذه القطعة",
  relatedCollections: "مجموعات ذات صلة",
  recentlyViewed: "شوهدت مؤخراً",
  viewing: (n) => `${n} ${n > 1 ? "أشخاص يتصفحون" : "شخص يتصفح"} هذه القطعة`,
  recentPurchase: (name, city) => `${name} من ${city} اقتنى للتو`,
  minutesAgo: (m) => (m < 2 ? "الآن" : `منذ ${m} دقيقة`),
  youMayLike: "قد تعجبك أيضاً",
  selectedForYou: "اخترناها لك",
  exploreCollection: "استكشف المجموعة",
  discoverMore: "اكتشف",
};

const strings: Record<Locale, PdpStrings> = { fr, en, ar };

export function getPdpStrings(locale: Locale): PdpStrings {
  return strings[locale] ?? fr;
}
